#[
autogenerated by docgen
loc: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim(78, 3)
rdoccmd: 
]#
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim", 78, 3).}:
  doAssert (big"42" * big"9") == big"378"

