#[
autogenerated by docgen
loc: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim(132, 3)
rdoccmd: 
]#
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim", 132, 3).}:
  doAssert (big"555" xor big"2") == big"553"

