#[
autogenerated by docgen
loc: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim(98, 3)
rdoccmd: 
]#
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim", 98, 3).}:
  doAssert big"2" < big"9"

