#[
autogenerated by docgen
loc: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim(91, 3)
rdoccmd: 
]#
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsbigints.nim", 91, 3).}:
  doAssert big"13" mod big"3" == big"1"
  doAssert big"-13" mod big"3" == big"-1"
  doAssert big"13" mod big"-3" == big"1"
  doAssert big"-13" mod big"-3" == big"-1"

