# autogenerated by docgen
# source: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jscore.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim"
