# autogenerated by docgen
# source: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jsconsole.nim
# rdoccmd: 
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim"
