# autogenerated by docgen
# source: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jsconsole.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_1.nim"
