# autogenerated by docgen
# source: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim"
