# autogenerated by docgen
# source: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/std/jsheaders.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/doc/html/nimcache/runnableExamples/jsheaders_examples_1.nim"
