#[
autogenerated by docgen
loc: /home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jsre.nim(68, 3)
rdoccmd: 
]#
import "/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jsre.nim"
{.line: ("/home/runner/work/nim-lang-Nim/nim-lang-Nim/lib/js/jsre.nim", 68, 3).}:
  let jsregex: RegExp = newRegExp(r"bcd", r"i")
  assert "abcd".endsWith jsregex

