name: GCC 14
on:
  pull_request:
  push:
    branches:
      - 'devel'


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        cpu: [amd64]
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60 # refs bug #18178
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 'Install node.js 20.x'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 'Install dependencies (Linux amd64)'
        if: runner.os == 'Linux' && matrix.cpu == 'amd64'
        run: |
          sudo apt update -qq
          sudo apt remove needrestart
          DEBIAN_FRONTEND='noninteractive' \
            sudo apt install --no-install-recommends -yq \
              libcurl4-openssl-dev libgc-dev libsdl1.2-dev libsfml-dev \
              valgrind libc6-dbg libblas-dev xorg-dev
      - name: 'Install dependencies (Linux amd64 gcc 14)'
        if: runner.os == 'Linux' && matrix.cpu == 'amd64'
        run: |
          sudo add-apt-repository universe
          sudo apt update -qq
          sudo apt install -y gcc-14 g++-14 libpcre3 liblapack-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14
      - name: 'Install dependencies (macOS)'
        if: runner.os == 'macOS'
        run: brew install boehmgc make sfml gtk+3
      - name: 'Install dependencies (Windows)'
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -e
          . ci/funs.sh
          nimInternalInstallDepsWindows
          echo_run echo "${{ github.workspace }}/dist/mingw64/bin" >> "${GITHUB_PATH}"

      - name: 'Add build binaries to PATH'
        shell: bash
        run: echo "${{ github.workspace }}/bin" >> "${GITHUB_PATH}"

      - name: 'NIM_TESTAMENT_DISABLE_SSL'
        shell: bash
        run: echo "NIM_TESTAMENT_DISABLE_SSL=1" >> $GITHUB_ENV

      - name: 'System information'
        shell: bash
        run: . ci/funs.sh && nimCiSystemInfo

      - name: 'Build csourcesAny'
        shell: bash
        run: . ci/funs.sh && nimBuildCsourcesIfNeeded CC=gcc ucpu='${{ matrix.cpu }}'

      - name: 'koch, Run CI'
        shell: bash
        run: . ci/funs.sh && nimInternalBuildKochAndRunCI
